[package]
name = "edge-executor"
version = "0.3.1"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "async", "executor"]
description = "Async executor suitable for embedded environments."
repository = "https://github.com/ivmarkov/edge-executor"
license = "MIT OR Apache-2.0"
readme = "README.md"

[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal", branch = "all-executors" }

[features]
default = ["std", "crossbeam-queue"]
std = ["alloc"]
alloc = ["esp-idf-hal?/alloc"]
wasm = ["std", "wasm-bindgen", "js-sys"]
esp-idf = ["esp-idf-hal"]

[dependencies]
heapless = { version = "0.7" }
crossbeam-queue = { version = "0.3", optional = true }
async-task = { version = "4", default-features = false }
waker-fn = { version = "1.1", default-features = false }
log = { version = "0.4", default-features = false }

# ESP-IDF dependencies
esp-idf-hal = { version = "0.41", default-features = false, optional = true, features = ["wake-from-isr"] }

# WASM dependencies
wasm-bindgen = { version = "0.2.82", optional = true }
js-sys = { version = "0.3", optional = true }

[dev-dependencies]
simple_logger = "2.2"

[build-dependencies]
embuild = "0.31.2"
