name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "50 4 * * *"
  workflow_dispatch:

env:
  rust_toolchain: stable

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - name: Setup
        run: rustup default ${{ env.rust_toolchain }}
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Build | Clippy
        run: cargo clippy --features std --no-deps -- -Dwarnings
      - name: Build | Compile
        run: cargo build
      - name: Build | Compile no_std
        run: cargo build --no-default-features --features portable-atomic,heapless --target riscv32imc-unknown-none-elf
      - name: Build | Test
        run: cargo test
